// Add your dependencies here

dependencies {
    api("com.github.GTNewHorizons:BuildCraft:7.1.57:dev")
    api("com.github.GTNewHorizons:CodeChickenCore:1.4.12:dev")
    implementation("curse.maven:cofh-lib-220333:2388748")

    compileOnly("com.github.GTNewHorizons:ProjectRed:4.12.33-GTNH:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:waila:1.19.23:api") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:ForgeMultipart:1.7.10:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:NotEnoughItems:2.8.93-GTNH:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:ForestryMC:4.11.15:api") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:EnderIO:2.10.25:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:CraftTweaker:3.4.6:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:QmunityLib:0.3.1:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-913-GTNH:dev") {
        transitive = false
    }
    compileOnly("com.github.GTNewHorizons:OpenComputers:1.12.38-GTNH:dev") {
        transitive = false
    }
    compileOnly("curse.maven:minefactory-reloaded-66672:2366150") {
        transitive = false
    }
    //compileOnly("curse.maven:applemilktea2-229325:2341197") {
    //    transitive = false
    //}
    compileOnly(files("dependencies/AppleMilkTea2-1.7.10_2.9n.jar"))
    compileOnly("curse.maven:mekanism-268560:2475797") {
        transitive = false
    }
    compileOnly("curse.maven:factorization-unofficial-392300:2990432") {
        transitive = false
    }
    compileOnly("curse.maven:blue-power-223099:2251307") {
        transitive = false
    }
    compileOnly(rfg.deobf('maven.modrinth:redlogic:59.1.13'))
    compileOnly(rfg.deobf('maven.modrinth:immibis-microblocks:59.1.2'))
    compileOnly(rfg.deobf('maven.modrinth:immibis-core:59.1.4'))

}
